name: Overtime Calculator CI/CD

on:
  push:
    branches:
      - main  # Workflow should trigger when changes are pushed to the main branch
  pull_request:
    branches:
      - main  # Workflow should trigger for pull requests to the main branch

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Set up Kotlin
      uses: olafurpg/setup-kotlin@v1
      with:
        kotlin-version: '1.6.10'

    - name: Build with Gradle
      run: ./gradlew build

    - name: Run tests with Gradle
      run: ./gradlew test

    - name: Package JAR
      run: ./gradlew jar

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: overtime-calculator-jar
        path: build/libs/*.jar
